### PR TITLE
Data Structure to Container Hierarchy

### LINKED ISSUE #6: Transform Array/Object Structure To Container Hierarchy
Right now there is no way to simply access an object/array data representation in a SOLID OOP way. Yet it could be very useful, especially in conjunction with other container decorators. At the same time, such a container representation could be useful in data structures, where every level would be represented by a container. This is already achieved in [dhii/map], which however uses outdated practices. Nevertheless, the factory approach that would produce a container hierarchy given an object/array data structure seems extremely useful.

[dhii/map]: https://github.com/dhii/map

### PR DESCRIPTION
**Pull request by XedinUnknown**
Closes #6.

### CODE REVIEW

**Review by mecha — COMMENTED** [review]
I don't like this approach for a number of reasons:

* It uses a factory (2 actually) to convert the structure
* The structure is converted all at once, rather than on-demand
* While I like to `Dictionary`, I feel like it doesn't fit in this repo.

We can instead provide a very simple container implementation which converts a structure into a container tree on demand. Thoughts?

---

**Edit**: See aa3a96da756238d701f1efd6245fe83257d4a61f

**Comment by XedinUnknown** [comment]
Didn't really understand what you mean by "on-demand". Like, only when a member is actually accessed? If so, I have no problem with that either, but it's just a different implementation. Feel free if you wanna provide one. It seems somewhat more complicated than what I already made, though.

I saw that for many cases, it's perfectly fine to convert the whole structure. It's the same amount of data, it's copy-on-write, and it seems perfect for DTO-like things, like REST API responses. In that paradigm, if the dictionary is just a map, then proper SoC would be to put the recursion logic into the factory.

As for not belonging to this repo, I'm not sure why you'd say that. It's a container, and this repo is for containers. They often get re-used together, which suggests they should be in the same package. Making a repo just for a `Dictionary` is way overkill, IMHO.

**Comment by XedinUnknown** [comment]
Saw your implementation. I like it. I suggest you file a PR with that, alongside this one.

_Edit_: That implementation is a container, but is not a map. Therefore it does not allow conversion of the container hierarchy back into a structure, e.g. one that can be sent to a REST API client. There are some other things that your implementation cannot do, and that mine can, but I appreciate how this is a slimmer container.

**Comment by mecha** [comment]
Oh right! Forgot about iteration. Still though, I think I'd prefer an on-demand approach, similar to how I wrote [`HierarchyContainer`][1].

Curious: what things can this implementation do that [`HierarchyContainer`][1] cannot? Besides iteration of course. I ask because it might make sense to take [`HierarchyContainer`][1] and turn it into a dictionary.

[1]: https://github.com/Dhii/containers/commit/aa3a96da756238d701f1efd6245fe83257d4a61f

**Comment by XedinUnknown** [comment]
Here's how I see this.

You have some unknown structure of arbitrary depth, and you want to be able to access its elements as you would access a hierarchy of containers. This is a good use-case for `HierarchyContainer`.

You have some known finite map, where you only really care about the first level, and you wan to be able to access its elements through a container. This is a good use-case for `Dictionary`.

This has been pending a long time. I'm gonna merge this for now. I don't think it will cause any problems, because both have good use-cases.

**Pull request merged**
