### PR TITLE
Initial Classes

### PR DESCRIPTION
**Pull request by XedinUnknown**
- Service provider.
- Composite service provider.
- Delegating container.
- Composite container.
- Caching container.

### CODE REVIEW

**Review by mecha — COMMENTED** [review]
Containers look good, but I have some questions and remarks.

----

First, what's the purpose of the `DelegatingContainer`? From the code it looks like it's just a Service Provider container that allows configuration of which container is passed to the service factories/extensions. Cool, but I don't think this is needed and its unneccesary complexity. Perhaps you prefer this approach, but I would not use it in my projects and instead do this:

```
$provider = /* some `ServiceProviderInterface` instance */;
$container = new CachingContainer(
    new DiContainer(
        new ServiceProviderContainer($provider)
    )
);
```

I'd make it so that the `DiContainer` is basically a decorator for another container, but if the inner container's returned value from `get()` is a callable, it invokes and returns the result. No other container would have this behavior. This would allow me to not care about these details have even thinner implementations.

----

This continues with the previous point, somewhat ...

The `CachingContainer` relies on generators. I would not do this, or at least I would write a second implementation that merely decorates another container and caches its returned values. This could be very useful on its own even for non-DI containers, especially for optimization long decorator chains.

----

Pet peeve: `CompositeCachingServiceProvider` is too long a name for my liking. Consider simply `CompositeServiceProvider`. The caching is an optimization.

**Comment by XedinUnknown** [comment]
> The `CachingContainer` relies on generators. I would not do this, or at least I would write a second implementation that merely decorates another container and caches its returned values.

The `CachingContainer` already merely decorates another container and caches its return value. The fact that it uses a generator function internally is an implementation detail. It just abstracts the "if not exists generate, then return" logic.

>  Cool, but I don't think this is needed and its unneccesary complexity. Perhaps you prefer this approach, but I would not use it in my projects and instead do this

I am pro separating the retrieval of the service value from definition resolution. But I still need the lookup delegation, which is why the `$parent` parameter exists. It's what allows passing the top container to the definitions. It is not possible to separate that from the resolution logic, which is why it must be done in the DI container, whatever that is.

> `CompositeCachingServiceProvider` is too long a name for my liking. Consider simply `CompositeServiceProvider`. The caching is an optimization.

The caching is an optimization that influences the behaviour of the API. If the underlying list of service providers changes, this will not be reflected in the result of subsequent calls. That's why the name.

**Comment by mecha** [comment]
> The CachingContainer already merely decorates another container and caches its return value. The fact that it uses a generator function internally is an implementation detail. It just abstracts the "if not exists generate, then return" logic.

I see. Missed that detail. Cool :smiley: 

> The caching is an optimization that influences the behaviour of the API. If the underlying list of service providers changes, this will not be reflected in the result of subsequent calls. That's why the name.

:+1: Understood

> I am pro separating the retrieval of the service value from definition resolution. But I still need the lookup delegation, which is why the $parent parameter exists. It's what allows passing the top container to the definitions. It is not possible to separate that from the resolution logic, which is why it must be done in the DI container, whatever that is.

If you put the resolving container at the end of the decorator chain, and you won't need lookup delegation, like I showed in my example. But I will reiterate; I have nothing against this class. I just don't see it being used. So I was hoping you'd give me a different reason for why it's needed, other than delegation lookup - maybe I was not seeing the real reason. But it looks like my assumption was correct. Therefore, I don't think this is necessary. But obviously it's existence isn't threatening anyone, other than the fact that it's a bit anti-decorator-pattern.

**Comment by XedinUnknown** [comment]
> If you put the resolving container at the end of the decorator chain, and you won't need lookup delegation, like I showed in my example.

Yea, but that's _your_ example. But that doesn't mean it will always be that way. So that's why it's "a-container-that-allows-passing-a-different-container-to-definitions". I would have made two separate classes, but I don't see how it's possible to separate the resolution and the-other-container-passing from each other.

> it's a bit anti-decorator-pattern

Well, the decorator pattern is just about wrapping an  interface implementation with another implementation of that interface. According to that definition, there's nothing wrong with this. If you mean more the Separation of Concerns aspect, then maybe just a little, but again it doesn't seem possible to separate those two concerns, so maybe they aren't so different.

> But obviously it's existence isn't threatening anyone

I hope this means I canz merge this. But would be great to get an actual approval furst.

**Review by mecha — APPROVED** [review]
I may not see the full utility of the classes in this PR, but I still approve of them.

**Comment by XedinUnknown** [comment]
So I tried separating the `DelegatingContainer` into a `ServiceContainer` and `DiContaiener`, as you suggest [here][1]:

> ```php
> $provider = /* some `ServiceProviderInterface` instance */;
> $container = new CachingContainer(
>     new DiContainer(
>         new ServiceProviderContainer($provider)
>     )
> );
> ```
> 
> I'd make it so that the `DiContainer` is basically a decorator for another container, but if the inner container's returned value from `get()` is a callable, it invokes and returns the result. No other container would have this behavior. This would allow me to not care about these details have even thinner implementations.

Apparently, the problem with this approach is that the extensions need to be resolved in order to be applied to the service. So, a resolution would already be taking place in `ServiceContainer`; just not for the service itself.

Do you still think it makes sense to separate them?

[1]: https://github.com/Dhii/containers/pull/1#pullrequestreview-236373644

**Comment by XedinUnknown** [comment]
I'm gona merge this. Modifications can come in other PRs.

**Pull request merged**
