### PR TITLE
Add missing return types

### LINKED ISSUE #24: Missing return type
Hey :) Here is missing return type in the `Dhii\Container\Dictionary::getIterator()`. [Here](https://github.com/Dhii/containers/blob/develop/src/Dictionary.php#L64) it is. It causes error in PHP 8.1+ and will cause a fatal error in PHP 9.
My guess it was just incidentally missing, and there is no intention behind missing return type.

### PR DESCRIPTION
**Pull request by strangerkir**
Closes #24.

### CODE REVIEW

**Comment by mecha** [comment]
LGTM. @XedinUnknown, requested review.

**Comment by XedinUnknown** [comment]
As I wrote [here](https://github.com/Dhii/containers/issues/24#issuecomment-1441732714), this fix seems to introduce a [PHP compatibility problem](https://3v4l.org/dcTqc#v5.6.40 ). Seeing that this package [requires at least PHP 7.1](https://github.com/Dhii/containers/blob/develop/composer.json#L19), however, this is not an issue.

**Comment by XedinUnknown** [comment]
@strangerkir, would you mind updating the changelog, please? Just add what you fixed in the standard format under the `next-version` header 🙏

**Comment by strangerkir** [comment]
@XedinUnknown  Done :slightly_smiling_face:

**Pull request merged**
